### ISSUE TITLE
Clarify license for generated code

### ISSUE THREAD

**Issue by jcjones** [mitls/hacl-star#17]
Other projects in your repository use the Apache 2 license ([mitls/mitls-fstar](https://github.com/mitls/mitls-fstar), for example).  Could you clarify the license in use for the [snapshots](https://github.com/mitls/hacl-star/tree/master/snapshots) and the tree in general?

**Comment by beurdouche** [comment]
I think we intend to release everything under Apache2, we'll discuss it internally and get back very soon (within 2 weeks) as we are planning to do a pre-release relatively soon.

**Comment by jedisct1** [comment]
If dual-licensing is an option, having that code available under a BSD license would also be awesome for integration within libsodium.

**Comment by beurdouche** [comment]
I don't feel like it is gonna be an issue. I am using Apache2 in NSS because it is our default License and was acceptable to RedHat and Mozilla but if it is blocking for libsodium, I see no objection in either a dual-licensing or an exception. Karthik is handling legal on this but feel free to ping me too when you want to move forward.

**Comment by jedisct1** [comment]
Karthik is on it :) This is awesome :)

**Comment by beurdouche** [comment]
Ok, this is done ! All the F* code is under Apache 2.0 and the generated C code is Licensed under MIT. We have the two different LICENSE files in `/` and `snapshots/`. The release will come with the header inside the files when necessary. :)
