### ISSUE TITLE
Easy HACL* setup

### ISSUE THREAD

**Issue by jkzinzindohoue** [mitls/hacl-star#35]
We have to provide an easy way for people to setup
- FStar (with appropriate revision number)
- Kremlin (with appropriate revision number)
- Z3 (with appropriate revision number)
- OpenSSL/LibSodium (optional, for benchmarks)

in order to run verification/extraction smoothly.

@msprotz is there already something in the everest script to achieve all of that ?
@beurdouche is docker a good option ? Is it already available ?

**Comment by beurdouche** [comment]
Docker is a good option and the Dockerfile is already available in the root directory.
I just improved today for people not using Docker by adding a Makefile.build that gives a 
`make prepare` target that will install opam packages, pull submodules and build F* and kremlin.
I need to update INSTALL.md with the hard prerequisites for non-docker users: OPAM and Z3

**Comment by jkzinzindohoue** [comment]
Right I had forgotten Z3 !
Plus we use specific Z3 builds from the everest repo so that needs to be clear as well.
I am not sure how to set all of this up but I can definitely help with testing.

**Comment by s-zanella** [comment]
I strongly suggest you use `everest`, which probably already does all that you need (including tracking Z3 builds). This will download prerequisites, set environment variables and checkout and build known working revisions of FStar, kremlin, hacl-star and Z3:
```
git clone -b stable https://github.com/project-everest/everest.git
cd everest
./everest check
./everest kremlin pull make
./everest FStar pull make
./everest hacl-star pull make [test verify]
```

There is a docker image on Docker Hub that you can get with `docker pull projecteverest/everest`. I lost track of how often the image is updated, or if the process is automated. @tahina-pro? 
Maybe you have good motives to maintain a separate Dockerfile, otherwise it'd be great if you could reuse or adapt the ones in `everest/.docker`.

**Comment by beurdouche** [comment]
Ok, the `README` now suggest to use Everest for the dependencies :
```
git clone -b stable https://github.com/project-everest/everest.git
cd everest
./everest check
./everest FStar pull make
./everest kremlin pull make
```
It then asks to get HaCl* and set `HACL_HOME`. I think this is quite ok, we can reopen the issue if we see that it doesn't work well enough for our users.
