### ISSUE TITLE
Excessive warnings when compiling with gcc -Wall

### ISSUE THREAD

**Issue by podhrmic** [mitls/hacl-star#51]
I am compiling hacl-c as a part of a larger project and can't change the `-Wall` attribute. It would be nice if the generated C code was without warnings - is that possible?

These warnings include: 

- missing parentheses

```
hacl-c/SHA2_512.c:220:28: warning: suggest parentheses around arithmetic in operand of '^' [-Wparentheses]
       + (a & b ^ a & c ^ b & c);
                          ~~^~~
```

- unused parameters

```
Ed25519.c:2872:13: warning: unused parameter 'tmp_ints' [-Wunused-parameter]
   uint64_t *tmp_ints
             ^~~~~~~~
```

- shadowing of variables

```
Ed25519.c:1889:17: warning: declaration of 'x30' shadows a previous local [-Wshadow]
       uint64_t *x30 = tmp + (uint32_t )5;
```

- incorrect return type (that is caused by #48 but I am not sure about a clean solution).

```
kremlib.c:32:1: warning: control reaches end of non-void function [-Wreturn-type]
 bool Prims_op_GreaterThan(Prims_int x, Prims_int y) { KRML_EXIT; }
```

**Comment by msprotz** [comment]
- `-Wparentheses` can be fixed by using `-fparentheses` when generating the snapshot
- unused parameters could be conceivably given a `__attribute(unused)__` annotation, but that would be GCC-specific, right?
- shadowing is expected: kremlin knows about the C scoping rules and generates correct code even in the face of shadowing (in theory)
- how would you like to exit cleanly in the case of an embedded target?

**Comment by beurdouche** [comment]
@podhrmic 
- I'll fix the parenthesis the next time I regenerate the snapshot (sometime next week)
- You PRed a patch for `FStar.h` adding `__attribute(unused)__`, we can't do that manual edit since it is generated code, so I'll close it but we'll track this here.
- I am not sure what we can do about that, it is a problem of the C compiler not being clever enough, think you may have to pass `-Wno-shadow` or something manually. @protz any better idea ?
- Interested in knowing what to do here too... :)

**Comment by podhrmic** [comment]
@beurdouche thanks for the inputs.

- Can the generated code (`FStar.h`) contain `__attribute(unused)__`? Looks like for both clang and GCC it works the same, not sure about compcert.
- I will try to add the flags manually and see how it goes.
- For the `exit()` - AFAIK an embedded system (at least in the bare-metal case) can't really exit from a process (if something crashes you end up in some kind of fault handler that is essentially just a `while(1)` loop). So the right way would be to never exit, but I am not sure in which cases can HACL* exit. Having the EXIT stubs that are  `while(1)` would be probably better than empty stubs I defined in #48 (at least the compiler wouldn't complain). Can HACL* exit in normal circumstances?

**Comment by msprotz** [comment]
for the incorrect return type you could do something along the lines of:
```
void __noreturn__ my_exit(__attribute__(unused) int errcode) {
  while(1);
}
```

then

```
#define KRML_HOST_EXIT my_exit
```

I believe that with my latest change in kremlib.h, you should be able to do things like the above for printf and malloc, too.

kremlib.h has to remain compilable on all platforms, so the unused attributes can't go in there, since in the general case, the arguments are, indeed, used.

Hope this helps,

Jonathan

**Comment by beurdouche** [comment]
Closing this in favor of https://github.com/mitls/hacl-star/issues/47
The two first cases have been handled in HACL.
I think `-no-shadow` might simply be a bit too strong for generated code but I'll keep track of it somewhere. the attribute unused cannot go to kremlib and should to be written in the caller code...
